import facebookIcon from '@/components/shared/facebook-icon';
import googleIcon from '@/components/shared/google-icon';
import {
  ArrowRight,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  X,
  Workflow,
  Book,
  Bookmark,
  Filter,
  Play,
  LayoutDashboard,
  Eye,
  EyeOff,
  House,
  Lock,
  AlertTriangle,
} from 'lucide-react';

/**
 * Icons - Centralized icon registry for lucide-react icons.
 * Use this object to reference icons throughout the app for consistency.
 */
export const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  book: Book,
  bookmark: Bookmark,
  filter: Filter,
  play: Play,
  dashboard: LayoutDashboard,
  eye: Eye,
  eyeOff: EyeOff,
  homeIcon: House,
  lock: Lock,
  google: googleIcon,
  facebook: facebookIcon,
  alertTriangle: AlertTriangle,
} as const;
