export const config = {
  apiUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api/v1',
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:9000',
  appBaseUrl: process.env.NEXT_PUBLIC_APP_BASE_URL || '.muhammedshafeeque.online',
  twitterHandle: process.env.NEXT_TWITTER_HANDLE || 'http://localhost:9000',
  googleSiteVerification: process.env.NEXT_GOOGLE_SITE_VERIFICATION || 'http://localhost:9000',
  environment: process.env.NODE_ENV || 'development',
  isProduction: process.env.NODE_ENV === 'production',
  isDevelopment: process.env.NODE_ENV === 'development',
  googlePublicClientId: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  nextAuthSecret: process.env.NEXTAUTH_SECRET,
  facebookClientId: process.env.FACEBOOK_CLIENT_ID,
  facebookClientSecret: process.env.FACEBOOK_CLIENT_SECRET,
  adminJwtSecret: process.env.JWT_ADMIN_SECRET,
  jwtSecret: process.env.JWT_SECRET,
  notificationWsUrl: process.env.NEXT_PUBLIC_NOTIFICATION_WS_URL || 'ws://localhost:4001',
  chatWsUrl: process.env.NEXT_PUBLIC_CHAT_WS_URL || 'ws://localhost:4009',
  adminJwtExpiry: process.env.ADMIN_JWT_TOKEN_EXPIRY,
  stripePublishableKey: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
} as const;
